services:
  videotoaudio:
    build:
      context: ./videotoaudio
    ports:
      - "3003:3003"
    volumes:
      - ./videotoaudio:/app

  uploadtostorage:
    build:
      context: ./uploadtostorage
    ports:
      - "3002:3002"
    volumes:
      - ./uploadtostorage:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
